version: '3'
services:
  mysql:
    image: postgres
    container_name: springboot-postgres
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - postgres
      restart: unless-stopped